spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost:3306/first_email
    username: root
    password: green502
  servlet:
    multipart:
      max-file-size: 5MB
  redis:
    host: localhost
    port: 6379

file:
  directory: D:\2024_BACK_JI\download\first_email

mybatis:
  mapper-locations: mappers/**/*.xml

springdoc:
  api-docs:
    version: openapi_3_1
  swagger-ui:
    path: /swagger
    operations-sorter: method
    default-model-expand-depth: 10
    default-models-expand-depth: 10
  cache:
    disabled: true

